name: Build and Push Docker Image
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  IMAGE_NAME: qbit-auto-upload
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Well, i remember this would clone the repository into the directory
      # That's why we can get the project files
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Log into the Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Dcoker Image
        run: |
          docker build -t \
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest .
      - name: Push the Docker Image
        run: |
          docker push \
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
      - name: Sync the docker-compose file into VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATEKEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          source: remote_server_deploy/docker-compose.yaml
          target: ${{ secrets.DEPLOY_PATH }}
      - name: Pull and Deploy Image Using SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST}}
          username: ${{ secrets.VPS_USERNAME}}
          key: ${{ secrets.VPS_PRIVATEKEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            set -e
            cd ${{ secrets.DEPLOY_PATH }}
            docker compose pull
            docker compose up -d
